export interface FishSpecies {
  id: string;
  name: string;       // slovenský názov
  latinName: string;
}

export const fishSpecies: FishSpecies[] = [
  { id: 'kapor', name: 'Kapor obecný', latinName: 'Cyprinus carpio' },
  { id: 'stuka', name: 'Šťuka severná', latinName: 'Esox lucius' },
  { id: 'zubac', name: 'Zubáč veľkoústy', latinName: 'Sander lucioperca' },
  { id: 'lien', name: 'Lieň sliznatý', latinName: 'Tinca tinca' },
  { id: 'sumec', name: 'Sumec veľký', latinName: 'Silurus glanis' },
  { id: 'karas_striebr', name: 'Karas strieborný', latinName: 'Carassius gibelio' },
  { id: 'karas_zlaty', name: 'Karas zlatistý', latinName: 'Carassius carassius' },
  { id: 'jalec_hlavaty', name: 'Jalec hlavatý', latinName: 'Squalius cephalus' },
  { id: 'jalec_maly', name: 'Jalec malý', latinName: 'Leuciscus leuciscus' },
  { id: 'pleskac_vysoke', name: 'Pleskáč vysoký', latinName: 'Abramis brama' },
  { id: 'pleskac_tupy', name: 'Pleskáč tupý', latinName: 'Blicca bjoerkna' },
  { id: 'ostriez', name: 'Ostriež zelenkavý', latinName: 'Perca fluviatilis' },
  { id: 'mrena', name: 'Mreňa severná', latinName: 'Barbus barbus' },
  { id: 'podustva', name: 'Podustva nosatá', latinName: 'Chondrostoma nasus' },
  { id: 'nosac', name: 'Nosáč stepný', latinName: 'Hypophthalmichthys nobilis' },
  { id: 'tolstolob', name: 'Tolstolob biely', latinName: 'Hypophthalmichthys molitrix' },
  { id: 'amur', name: 'Amur biely', latinName: 'Ctenopharyngodon idella' },
  { id: 'losos', name: 'Losos atlantický', latinName: 'Salmo salar' },
  { id: 'pstruh_potocny', name: 'Pstruh potočný', latinName: 'Salmo trutta fario' },
  { id: 'pstruh_duhovy', name: 'Pstruh dúhový', latinName: 'Oncorhynchus mykiss' },
  { id: 'lipan', name: 'Lipáň tymiánový', latinName: 'Thymallus thymallus' },
  { id: 'sih', name: 'Sivoň americký', latinName: 'Salvelinus fontinalis' },
  { id: 'sih_pelad', name: 'Síh peľád', latinName: 'Coregonus peled' },
  { id: 'sih_maraena', name: 'Síh maréna', latinName: 'Coregonus maraena' },
  { id: 'bolen', name: 'Boleň dravý', latinName: 'Leuciscus aspius' },
  { id: 'plotica', name: 'Plotica červenooká', latinName: 'Rutilus rutilus' },
  { id: 'plotica_perlovitka', name: 'Plotica perlovitka', latinName: 'Scardinius erythrophthalmus' },
  { id: 'uhor', name: 'Úhor európsky', latinName: 'Anguilla anguilla' },
  { id: 'kanka', name: 'Kanec dunajský', latinName: 'Zingel zingel' },
  { id: 'kolok', name: 'Kolok veľký', latinName: 'Zingel streber' },
  { id: 'hrebenacka', name: 'Hrebenačka vysoká', latinName: 'Gymnocephalus cernua' },
  { id: 'hrebenacka_bodkana', name: 'Hrebenačka bodkovaná', latinName: 'Gymnocephalus schraetser' },
  { id: 'piskor', name: 'Piškor európsky', latinName: 'Misgurnus fossilis' },
  { id: 'piskor_potocny', name: 'Piškor potočný', latinName: 'Cobitis taenia' },
  { id: 'mrenka', name: 'Mrenka škvrnitá', latinName: 'Barbatula barbatula' },
  { id: 'hruz', name: 'Hrúz severný', latinName: 'Gobio gobio' },
  { id: 'hruz_bieloplutvovy', name: 'Hrúz bieloplutvový', latinName: 'Romanogobio albipinnatus' },
  { id: 'piskar', name: 'Piskáč pruhovaný', latinName: 'Alburnoides bipunctatus' },
  { id: 'uklej', name: 'Ukleja horná', latinName: 'Alburnus alburnus' },
  { id: 'orvica', name: 'Orvica fúzatá', latinName: 'Rhodeus amarus' },
  { id: 'sliz', name: 'Slíž severný', latinName: 'Nemacheilus barbatulus' },
  { id: 'kapor_striebr', name: 'Kapor strieborný', latinName: 'Carassius auratus' },
  { id: 'amur_cerny', name: 'Amur čierny', latinName: 'Mylopharyngodon piceus' },
  { id: 'bufallo', name: 'Bufelov veľkoústy', latinName: 'Ictiobus cyprinellus' },
  { id: 'candak', name: 'Candát obecný', latinName: 'Sander volgensis' },
  { id: 'jesetr_maly', name: 'Jeseter malý', latinName: 'Acipenser ruthenus' },
  { id: 'jesetr_rusky', name: 'Jeseter ruský', latinName: 'Acipenser gueldenstaedtii' },
  { id: 'viza', name: 'Vyza veľká', latinName: 'Huso huso' },
  { id: 'blatnak', name: 'Bletnák tmavý', latinName: 'Umbra krameri' },
  { id: 'strkac', name: 'Štrukáč ostnatý', latinName: 'Gasterosteus aculeatus' },
  { id: 'hlavac', name: 'Hlaváč riečny', latinName: 'Neogobius fluviatilis' },
  { id: 'hlavac_mramor', name: 'Hlaváč mramorovaný', latinName: 'Neogobius melanostomus' },
  { id: 'ostriez_pompano', name: 'Ostriež slnečnicový', latinName: 'Lepomis gibbosus' },
  { id: 'bass_zeleny', name: 'Bas zelený', latinName: 'Micropterus salmoides' },
  { id: 'pstruh_jazern', name: 'Pstruh jazerný', latinName: 'Salmo trutta lacustris' },
  { id: 'sik_biely', name: 'Sík biely', latinName: 'Coregonus lavaretus' },
  { id: 'tajmen', name: 'Tajmeň dunajský', latinName: 'Hucho hucho' },
  { id: 'nosac_strak', name: 'Nosáč strakatý', latinName: 'Aristichthys nobilis' },
  { id: 'mrena_dunajska', name: 'Mreňa dunajská', latinName: 'Barbus petenyi' },
  { id: 'mrena_karpatska', name: 'Mreňa karpatská', latinName: 'Barbus cyclolepis waleckii' },
  { id: 'jalec_pruhov', name: 'Jalec pruhovaný', latinName: 'Leuciscus souffia' },
  { id: 'jalec_tlen', name: 'Jalec tlstý', latinName: 'Leuciscus idus' },
  { id: 'pstruh_kapor', name: 'Pstruhový kapor', latinName: 'Cyprinus carpio (mirror)' },
  { id: 'kapor_koi', name: 'Kapor koi', latinName: 'Cyprinus carpio koi' },
  { id: 'kapor_koze', name: 'Kapor kožený', latinName: 'Cyprinus carpio (leather)' },
  { id: 'karas_hyb', name: 'Karas hybrid', latinName: 'Carassius sp. hybrid' },
  { id: 'zubac_volzsky', name: 'Zubáč Volžský', latinName: 'Sander volgensis (Volga)' },
  { id: 'hrebenacka_zlta', name: 'Hrebenačka žltá', latinName: 'Gymnocephalus cernuus' },
  { id: 'belica', name: 'Belica európska', latinName: 'Leucaspius delineatus' },
  { id: 'parma', name: 'Parma dúhová', latinName: 'Pungitius platygaster' },
  { id: 'cejn_velky', name: 'Cejn veľký', latinName: 'Abramis sapa' },
  { id: 'olesnica', name: 'Olešnica potočná', latinName: 'Squalius sp.' },
  { id: 'vrezub', name: 'Vrezúb veľký', latinName: 'Rutilus frisii' },
  { id: 'tolstolob_hyb', name: 'Tolstolob hybrid', latinName: 'Hypophthalmichthys sp. hybrid' },
  { id: 'sumcek_americky', name: 'Sumček americký', latinName: 'Ameiurus nebulosus' },
  { id: 'sumcek_cierny', name: 'Sumček čierny', latinName: 'Ameiurus melas' },
  { id: 'sumcek_skvrnity', name: 'Sumček škvrnitý', latinName: 'Ictalurus punctatus' },
  { id: 'pajalec', name: 'Pájalec pásikovitý', latinName: 'Pseudorasbora parva' },
  { id: 'stika_amur', name: 'Šťuka amurská', latinName: 'Esox reichertii' },
  { id: 'bolen_bielooci', name: 'Boleň bieloočkový', latinName: 'Leuciscus borysthenicus' },
  { id: 'cejnok_piras', name: 'Cejnok pirát', latinName: 'Pelecus cultratus' },
  { id: 'murenka', name: 'Mieňa sladkovodná', latinName: 'Lota lota' },
  { id: 'pleskac_vojens', name: 'Pleskáč vojenský', latinName: 'Abramis ballerus' },
  { id: 'piskor_zeleny', name: 'Piškor zelený', latinName: 'Cobitis elongata' },
  { id: 'vretenica', name: 'Vretenica potočná', latinName: 'Zingel sp.' },
  { id: 'hruz_bielopiav', name: 'Hrúz bieloplavý', latinName: 'Gobio albipinnatus' },
  { id: 'hlavacik', name: 'Hlaváčik bodkovaný', latinName: 'Cottus gobio' },
  { id: 'rybka_hork', name: 'Rybka horká', latinName: 'Rhodeus amarus (bitter)' },
  { id: 'mrena_dunajska2', name: 'Mreňa dunajská veľká', latinName: 'Barbus barbus danubii' },
  { id: 'kapor_izraelsky', name: 'Kapor izraelský', latinName: 'Cyprinus carpio Israeli' },
  { id: 'uhor_americky', name: 'Úhor americký', latinName: 'Anguilla rostrata' },
  { id: 'ostriez_ricky', name: 'Ostriež ríčny', latinName: 'Perca fluviatilis (large)' },
  { id: 'pstruh_sk', name: 'Pstruh slovenský', latinName: 'Salmo trutta m. fario' },
  { id: 'lipan_dunajsky', name: 'Lipáň dunajský', latinName: 'Thymallus thymallus (Danube)' },
  { id: 'sikouz', name: 'Síkouz alpský', latinName: 'Cottus poecilopus' },
  { id: 'zubac_candak', name: 'Zubáč candák', latinName: 'Sander lucioperca (large)' },
  { id: 'candak_volzsky', name: 'Candát Volžský', latinName: 'Sander volgensis (Volga form)' },
  { id: 'pleskac_okovany', name: 'Pleskáč okovaný', latinName: 'Abramis brama orientalis' },
  { id: 'kleniky', name: 'Kleník riečny', latinName: 'Leuciscus cephalus' },
  { id: 'karas_spany', name: 'Karas španielsky', latinName: 'Carassius carassius iberian' },
  { id: 'hruz_prasiatko', name: 'Hrúz prasiatko', latinName: 'Gobio kesslerii' },
  { id: 'jesetr_hviezd', name: 'Jeseter hviezdny', latinName: 'Acipenser stellatus' },
  { id: 'jesetr_syber', name: 'Jeseter sibirský', latinName: 'Acipenser baerii' },
];

export function searchFishSpecies(query: string): FishSpecies[] {
  if (!query) return fishSpecies;
  const lower = query.toLowerCase();
  return fishSpecies.filter(s =>
    s.name.toLowerCase().includes(lower) ||
    s.latinName.toLowerCase().includes(lower)
  );
}
